"""Deterministic preparatory prompts and official resource links.

Every prompt here is selected by an explicit rule over calculated figures. None
of this text is generated by a model, and none of it recommends a financial
action: the prompts point the user at things to check and at official channels
that decide their own outcomes.
"""

from .models import (
    BaselineFinances,
    BaselineSummary,
    OfficialResource,
    PreparatoryAction,
    ScenarioSummary,
    ShockScenario,
)

DISCLAIMERS: tuple[str, ...] = (
    "These figures are estimates calculated from the values you entered. They are not a prediction of what will happen.",
    "Resilience does not provide financial advice and does not hold or transfer your money.",
    "The estimate assumes your essential expenses and fixed work costs stay the same during the scenario.",
    "Support scheme eligibility is decided only by the relevant government agency.",
)

# Official Singapore government entry points. These are top-level departmental
# sites rather than deep links, because deep paths change without notice and a
# broken link during a shock is worse than one extra click.
OFFICIAL_RESOURCES: tuple[OfficialResource, ...] = (
    OfficialResource(
        id="supportgowhere",
        name="SupportGoWhere",
        description="Government directory of Singapore support schemes, with an eligibility checker.",
        url="https://supportgowhere.life.gov.sg",
        last_reviewed="2026-09-01",
    ),
    OfficialResource(
        id="msf",
        name="Ministry of Social and Family Development",
        description="ComCare short-to-medium-term assistance, administered through Social Service Offices.",
        url="https://www.msf.gov.sg",
        last_reviewed="2026-09-01",
    ),
    OfficialResource(
        id="mom",
        name="Ministry of Manpower",
        description="Platform worker protections, including work injury compensation.",
        url="https://www.mom.gov.sg",
        last_reviewed="2026-09-01",
    ),
    OfficialResource(
        id="cpf",
        name="Central Provident Fund Board",
        description="MediSave and CPF information for self-employed and platform workers.",
        url="https://www.cpf.gov.sg",
        last_reviewed="2026-09-01",
    ),
)

_RESOURCES_BY_ID = {resource.id: resource for resource in OFFICIAL_RESOURCES}


def _sgd(cents: int) -> str:
    sign = "-" if cents < 0 else ""
    whole, remainder = divmod(abs(cents), 100)
    return f"{sign}S${whole:,}.{remainder:02d}"


def _weeks(count: int) -> str:
    return "1 week" if count == 1 else f"{count} weeks"


def build_actions(
    baseline: BaselineFinances,
    scenario: ShockScenario,
    baseline_summary: BaselineSummary,
    scenario_summary: ScenarioSummary,
) -> tuple[PreparatoryAction, ...]:
    """Select preparatory prompts from the calculated figures.

    Rules are evaluated in a fixed order so the same scenario always produces
    the same prompts in the same sequence.
    """
    actions: list[PreparatoryAction] = []

    if baseline_summary.weekly_surplus_cents < 0:
        actions.append(
            PreparatoryAction(
                id="baseline-deficit",
                title="A normal week is already short",
                detail=(
                    f"Before this scenario, your usual week is estimated to fall short by "
                    f"{_sgd(-baseline_summary.weekly_surplus_cents)}. The figures below start from that position."
                ),
                severity="attention",
                resource_ids=("supportgowhere", "msf"),
            )
        )

    first_shortfall = scenario_summary.first_shortfall_week
    if first_shortfall is not None and scenario.weeks_affected == 0:
        # Nothing about earnings changed, so the shortfall wording must not
        # refer to a disruption or to income recovering.
        actions.append(
            PreparatoryAction(
                id="savings-run-out-without-income-change",
                title="Savings run out even with earnings unchanged",
                detail=(
                    f"Your earnings stay the same in this scenario, but your savings are still estimated to run "
                    f"out in week {first_shortfall}, leaving about "
                    f"{_sgd(scenario_summary.total_shortfall_cents)} uncovered over the period shown."
                ),
                severity="attention",
                resource_ids=("supportgowhere", "msf"),
            )
        )
    elif first_shortfall is not None and first_shortfall <= scenario.weeks_affected:
        actions.append(
            PreparatoryAction(
                id="buffer-runs-out-during-shock",
                title="Savings run out before the scenario ends",
                detail=(
                    f"This estimate has your savings covering {_weeks(scenario_summary.buffer_runway_weeks or 0)} "
                    f"of a {_weeks(scenario.weeks_affected)} disruption, with an estimated "
                    f"{_sgd(scenario_summary.total_shortfall_cents)} not covered over the period shown."
                ),
                severity="attention",
                resource_ids=("supportgowhere", "msf"),
            )
        )
    elif first_shortfall is not None:
        actions.append(
            PreparatoryAction(
                id="buffer-runs-out-after-shock",
                title="Savings run out while income is recovering",
                detail=(
                    f"Your savings are estimated to cover the disruption itself but run out in week "
                    f"{first_shortfall}, before earnings return to their usual level."
                ),
                severity="attention",
                resource_ids=("supportgowhere",),
            )
        )

    if scenario_summary.buffer_holds_through_horizon:
        actions.append(
            PreparatoryAction(
                id="buffer-holds",
                title="Savings cover this scenario",
                detail=(
                    f"Your savings are estimated to last through all {_weeks(scenario_summary.horizon_weeks)} shown, "
                    f"ending at about {_sgd(scenario_summary.buffer_at_horizon_cents)}, "
                    f"with a low point of {_sgd(scenario_summary.lowest_buffer_cents)} in week "
                    f"{scenario_summary.lowest_buffer_week}."
                ),
                severity="info",
                resource_ids=("supportgowhere",),
            )
        )

    if baseline.weekly_fixed_work_costs_cents > 0 and scenario.income_reduction_percent > 0:
        actions.append(
            PreparatoryAction(
                id="fixed-work-costs-continue",
                title="Fixed work costs continue",
                detail=(
                    f"{_sgd(baseline.weekly_fixed_work_costs_cents)} of weekly work costs are treated as fixed, so they "
                    f"continue even in a week with reduced earnings. It is worth checking whether rental, "
                    f"insurance, or subscription costs can be paused or reduced."
                ),
                severity="info",
            )
        )

    if scenario.unexpected_cost_cents > baseline.emergency_savings_cents:
        actions.append(
            PreparatoryAction(
                id="one-off-cost-exceeds-buffer",
                title="The one-off cost is larger than your savings",
                detail=(
                    f"The {_sgd(scenario.unexpected_cost_cents)} cost is more than your current "
                    f"{_sgd(baseline.emergency_savings_cents)} in savings, so part of it is unfunded from week 1 "
                    f"in this estimate."
                ),
                severity="attention",
                resource_ids=("supportgowhere", "msf"),
            )
        )

    if scenario_summary.total_shortfall_cents > 0:
        actions.append(
            PreparatoryAction(
                id="check-support-schemes",
                title="Check which support you could apply for",
                detail=(
                    "The Scheme Navigator can pre-screen you against maintained scheme rules. "
                    "Only the relevant agency can confirm eligibility."
                ),
                severity="info",
                resource_ids=("supportgowhere", "msf", "mom", "cpf"),
            )
        )

    return tuple(actions)


def resources_for_actions(
    actions: tuple[PreparatoryAction, ...],
) -> tuple[OfficialResource, ...]:
    """Return the official resources referenced by the selected prompts, in order."""
    ordered_ids: list[str] = []
    for action in actions:
        for resource_id in action.resource_ids:
            if resource_id not in ordered_ids:
                ordered_ids.append(resource_id)
    return tuple(_RESOURCES_BY_ID[resource_id] for resource_id in ordered_ids)
