/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/foundation/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_v1_foundation_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Onboarding */
        put: operations["onboarding_api_v1_foundation_onboarding_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Profile Update */
        patch: operations["profile_update_api_v1_foundation_profile_patch"];
        trace?: never;
    };
    "/api/v1/foundation/recurring-work-costs/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Recurring Put */
        put: operations["recurring_put_api_v1_foundation_recurring_work_costs__item_id__put"];
        post?: never;
        /** Recurring Delete */
        delete: operations["recurring_delete_api_v1_foundation_recurring_work_costs__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/essential-expenses/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Essential Put */
        put: operations["essential_put_api_v1_foundation_essential_expenses__item_id__put"];
        post?: never;
        /** Essential Delete */
        delete: operations["essential_delete_api_v1_foundation_essential_expenses__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weeks List */
        get: operations["weeks_list_api_v1_foundation_weeks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/weeks/{week_start}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week Get */
        get: operations["week_get_api_v1_foundation_weeks__week_start__get"];
        /** Week Put */
        put: operations["week_put_api_v1_foundation_weeks__week_start__put"];
        post?: never;
        /** Week Delete */
        delete: operations["week_delete_api_v1_foundation_weeks__week_start__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transaction Create */
        post: operations["transaction_create_api_v1_foundation_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Transaction Delete */
        delete: operations["transaction_delete_api_v1_foundation_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Data Reset */
        delete: operations["data_reset_api_v1_foundation_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-reality/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Breakdown */
        post: operations["post_breakdown_api_v1_income_reality_breakdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheme-navigator/questionnaire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Questionnaire
         * @description Returns only the questions actually needed by the currently loaded
         *     scheme rules, in a stable display order.
         */
        get: operations["get_questionnaire_api_v1_scheme_navigator_questionnaire_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheme-navigator/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate
         * @description Evaluates the submitted answers against every loaded scheme rule.
         *
         *     Any field a rule needs that is absent from ``answers`` yields a
         *     ``missing_information`` result for that scheme rather than a guess.
         */
        post: operations["evaluate_api_v1_scheme_navigator_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheme-navigator/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain Result
         * @description Rephrases an already-decided result in plain language.
         *
         *     The status is decided by the evaluator and only described here. If the
         *     model is unconfigured or unreachable, this returns a deterministic
         *     explanation rather than an error.
         */
        post: operations["explain_result_api_v1_scheme_navigator_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheme-navigator/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Turn
         * @description Answers a scoped question about the loaded schemes and this app.
         *
         *     Degrades to a canned reply when the model is unconfigured or
         *     unreachable, so the chat panel never surfaces a server error.
         */
        post: operations["chat_turn_api_v1_scheme_navigator_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenario-simulator/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate cash flow and emergency-buffer runway for one financial shock */
        post: operations["simulate_scenario_api_v1_scenario_simulator_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_savings_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_v1_savings_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings-goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Goal */
        delete: operations["delete_goal_api_v1_savings_goals__goal_id__delete"];
        options?: never;
        head?: never;
        /** Patch Goal */
        patch: operations["patch_goal_api_v1_savings_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/savings-goals/{goal_id}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Contribution */
        post: operations["add_contribution_api_v1_savings_goals__goal_id__contributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/savings-goals/{goal_id}/contributions/{contribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Contribution */
        delete: operations["delete_contribution_api_v1_savings_goals__goal_id__contributions__contribution_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resilience-jar/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_v1_resilience_jar_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resilience-jar/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Plan */
        patch: operations["patch_plan_api_v1_resilience_jar_plan_patch"];
        trace?: never;
    };
    "/api/v1/resilience-jar/opening-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Opening Balance */
        put: operations["set_opening_balance_api_v1_resilience_jar_opening_balance_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resilience-jar/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Contribution */
        post: operations["create_contribution_api_v1_resilience_jar_contributions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resilience-jar/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Withdrawal */
        post: operations["create_withdrawal_api_v1_resilience_jar_withdrawals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resilience-jar/contributions/{contribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Contribution */
        delete: operations["delete_contribution_api_v1_resilience_jar_contributions__contribution_id__delete"];
        options?: never;
        head?: never;
        /** Update Contribution */
        patch: operations["update_contribution_api_v1_resilience_jar_contributions__contribution_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmountGoalInput */
        AmountGoalInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "amount";
            /** Amount Cents */
            amount_cents: number;
        };
        /** AssumptionsIn */
        AssumptionsIn: {
            /**
             * Apply Cpf
             * @default false
             */
            apply_cpf: boolean;
            /**
             * Cpf Rate Bps
             * @default 800
             */
            cpf_rate_bps: number;
        };
        /** BaselineFinancesPayload */
        BaselineFinancesPayload: {
            /** Weekly Gross Earnings Cents */
            weekly_gross_earnings_cents: number;
            /** Weekly Variable Work Costs Cents */
            weekly_variable_work_costs_cents: number;
            /** Weekly Fixed Work Costs Cents */
            weekly_fixed_work_costs_cents: number;
            /** Weekly Essential Expenses Cents */
            weekly_essential_expenses_cents: number;
            /** Emergency Savings Cents */
            emergency_savings_cents: number;
        };
        /** BaselineSummaryResponse */
        BaselineSummaryResponse: {
            /** Weekly Gross Earnings Cents */
            weekly_gross_earnings_cents: number;
            /** Weekly Work Costs Cents */
            weekly_work_costs_cents: number;
            /** Weekly Net Work Income Cents */
            weekly_net_work_income_cents: number;
            /** Weekly Essential Expenses Cents */
            weekly_essential_expenses_cents: number;
            /** Weekly Surplus Cents */
            weekly_surplus_cents: number;
            /** Emergency Savings Cents */
            emergency_savings_cents: number;
            /** Emergency Savings Weeks Of Essentials */
            emergency_savings_weeks_of_essentials: number | null;
            /** Runway Weeks */
            runway_weeks: number | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /**
         * ChatRequest
         * @description A chatbot turn.
         *
         *     Unlike the explainer, this deliberately carries the user's ``answers``:
         *     the assistant is expected to field questions like "why didn't I match
         *     WIS?", which cannot be answered without them. That is a conscious
         *     privacy trade -- see documentation/features/scheme-navigator.md.
         */
        ChatRequest: {
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
            /** Answers */
            answers?: {
                [key: string]: unknown;
            };
            /** Results */
            results?: components["schemas"]["SchemeResult"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Is Ai Generated */
            is_ai_generated: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** ContributionPatch */
        ContributionPatch: {
            /** Amount Cents */
            amount_cents?: number | null;
            /** Contribution Date */
            contribution_date?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ContributionWrite */
        ContributionWrite: {
            /** Amount Cents */
            amount_cents: number;
            /**
             * Contribution Date
             * Format: date
             */
            contribution_date: string;
            /** Note */
            note?: string | null;
        };
        /** CoverageGoalInput */
        CoverageGoalInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "coverage";
            /** Weeks */
            weeks: number;
        };
        /** EarningInput */
        EarningInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Platformcode
             * @enum {string}
             */
            platformCode: "grab" | "gojek" | "tada" | "deliveroo" | "foodpanda" | "lalamove" | "other";
            /** Platformlabel */
            platformLabel?: string | null;
            /** Amountcents */
            amountCents: number;
        };
        /** EssentialExpenseInput */
        EssentialExpenseInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "housing" | "food" | "transport" | "utilities" | "healthcare" | "caregiving" | "debt" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
        };
        /** EssentialExpenseResponse */
        EssentialExpenseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "housing" | "food" | "transport" | "utilities" | "healthcare" | "caregiving" | "debt" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** EvaluationRequest */
        EvaluationRequest: {
            /** Answers */
            answers?: {
                [key: string]: unknown;
            };
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Results */
            results: components["schemas"]["SchemeResult"][];
        };
        /**
         * ExplanationRequest
         * @description Asks for a plain-language explanation of an already-decided result.
         *
         *     The caller sends back a ``SchemeResult`` the evaluator produced. The
         *     explainer never re-derives the status, so the request carries the
         *     outcome rather than the answers that led to it.
         */
        ExplanationRequest: {
            /** Rule Id */
            rule_id: string;
            /** Answers */
            answers?: {
                [key: string]: unknown;
            };
        };
        /** ExplanationResponse */
        ExplanationResponse: {
            /** Summary */
            summary: string;
            /** Next Steps */
            next_steps?: string[];
            /** Source Urls */
            source_urls?: string[];
            /** Is Ai Generated */
            is_ai_generated: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** FoundationBootstrap */
        FoundationBootstrap: {
            profile: components["schemas"]["ProfileResponse"];
            /** Recurringworkcosts */
            recurringWorkCosts: components["schemas"]["RecurringWorkCostResponse"][];
            /** Essentialexpenses */
            essentialExpenses: components["schemas"]["EssentialExpenseResponse"][];
            /** Weeklyentries */
            weeklyEntries: components["schemas"]["WeeklyEntryResponse"][];
            /** Transactions */
            transactions?: components["schemas"]["TransactionResponse"][];
            /**
             * Syncedat
             * Format: date-time
             */
            syncedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeRealityRequest */
        IncomeRealityRequest: {
            /** Weeks */
            weeks: components["schemas"]["WeeklyEntryIn"][];
            assumptions?: components["schemas"]["AssumptionsIn"];
        };
        /** IncomeRealityResponse */
        IncomeRealityResponse: {
            /** Weeks */
            weeks: components["schemas"]["WeekBreakdownOut"][];
            trend: components["schemas"]["TrendSummaryOut"];
            assumptions_applied: components["schemas"]["AssumptionsIn"];
        };
        /** InputSnapshot */
        InputSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sourceid */
            sourceId?: string | null;
            /**
             * Inputkind
             * @enum {string}
             */
            inputKind: "recurring_work_cost" | "essential_expense";
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
        };
        /** OfficialResourceResponse */
        OfficialResourceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Url */
            url: string;
            /** Last Reviewed */
            last_reviewed: string;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /** Emergencysavingscents */
            emergencySavingsCents: number;
            /** Recurringworkcosts */
            recurringWorkCosts?: components["schemas"]["RecurringWorkCostInput"][];
            /** Essentialexpenses */
            essentialExpenses?: components["schemas"]["EssentialExpenseInput"][];
            /** Firstweekstart */
            firstWeekStart?: string | null;
            firstWeek?: components["schemas"]["WeeklyEntryUpsert"] | null;
        };
        /** OpeningBalanceRequest */
        OpeningBalanceRequest: {
            /** Amount Cents */
            amount_cents: number;
        };
        /** PlanPatch */
        PlanPatch: {
            recommendation_method?: components["schemas"]["RecommendationMethod"] | null;
            target_frequency?: components["schemas"]["TargetFrequency"] | null;
            /** Target Amount Cents */
            target_amount_cents?: number | null;
            /** Weekly Target Cents */
            weekly_target_cents?: number | null;
            status?: components["schemas"]["PlanStatus"] | null;
            /** Goal */
            goal?: (components["schemas"]["AmountGoalInput"] | components["schemas"]["CoverageGoalInput"]) | null;
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "active" | "paused";
        /** PlatformEarningIn */
        PlatformEarningIn: {
            /** Platform */
            platform: string;
            /** Gross Cents */
            gross_cents: number;
        };
        /** PlatformEarningOut */
        PlatformEarningOut: {
            /** Platform */
            platform: string;
            /** Gross Cents */
            gross_cents: number;
        };
        /** PreparatoryActionResponse */
        PreparatoryActionResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Severity */
            severity: string;
            /** Resource Ids */
            resource_ids: string[];
        };
        /** ProfileResponse */
        ProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Currency */
            currency: string;
            /** Timezone */
            timezone: string;
            /** Onboardingcompleted */
            onboardingCompleted: boolean;
            /** Latestemergencysavingscents */
            latestEmergencySavingsCents: number;
            /**
             * Emergencyfundbalancecents
             * @default 0
             */
            emergencyFundBalanceCents: number;
            /** Displayname */
            displayName?: string | null;
            /** Phonenumber */
            phoneNumber?: string | null;
            /** Dateofbirth */
            dateOfBirth?: string | null;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Displayname */
            displayName?: string | null;
            /** Phonenumber */
            phoneNumber?: string | null;
            /** Dateofbirth */
            dateOfBirth?: string | null;
        };
        /**
         * QuestionnaireField
         * @description One prompt shown to the user. Derived from whichever scheme rules
         *     actually reference it, not hand-written per scheme.
         */
        QuestionnaireField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Field Type
             * @enum {string}
             */
            field_type: "number" | "boolean" | "select" | "date";
            /** Help Text */
            help_text?: string | null;
            /** Unit */
            unit?: string | null;
            /** Options */
            options?: components["schemas"]["SelectOption"][] | null;
            /** Min Value */
            min_value?: number | null;
            /** Max Value */
            max_value?: number | null;
        };
        /**
         * RecommendationMethod
         * @enum {string}
         */
        RecommendationMethod: "conservative_4_week" | "latest_week";
        /** RecurringWorkCostInput */
        RecurringWorkCostInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "vehicle_rental" | "insurance" | "subscription" | "equipment" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
        };
        /** RecurringWorkCostResponse */
        RecurringWorkCostResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "vehicle_rental" | "insurance" | "subscription" | "equipment" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SavingsGoalContributionCreate */
        SavingsGoalContributionCreate: {
            /** Amountcents */
            amountCents: number;
            /**
             * Contributedon
             * Format: date
             */
            contributedOn: string;
            /** Note */
            note?: string | null;
        };
        /** SavingsGoalContributionResponse */
        SavingsGoalContributionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Contributedon
             * Format: date
             */
            contributedOn: string;
            /** Note */
            note: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** SavingsGoalCreate */
        SavingsGoalCreate: {
            /** Name */
            name: string;
            /** Targetcents */
            targetCents: number;
            /** Targetdate */
            targetDate?: string | null;
        };
        /** SavingsGoalListResponse */
        SavingsGoalListResponse: {
            /** Goals */
            goals: components["schemas"]["SavingsGoalResponse"][];
        };
        /** SavingsGoalPatch */
        SavingsGoalPatch: {
            /** Name */
            name?: string | null;
            /** Targetcents */
            targetCents?: number | null;
            /** Targetdate */
            targetDate?: string | null;
            /** Status */
            status?: ("active" | "completed" | "archived") | null;
        };
        /** SavingsGoalResponse */
        SavingsGoalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Targetcents */
            targetCents: number;
            /** Targetdate */
            targetDate: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "archived";
            /** Savedcents */
            savedCents: number;
            /** Remainingcents */
            remainingCents: number;
            /** Reached */
            reached: boolean;
            /** Suggestedweeklycents */
            suggestedWeeklyCents: number | null;
            /** Contributions */
            contributions: components["schemas"]["SavingsGoalContributionResponse"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ScenarioResultResponse */
        ScenarioResultResponse: {
            baseline: components["schemas"]["BaselineSummaryResponse"];
            scenario: components["schemas"]["ScenarioSummaryResponse"];
            /** Weeks */
            weeks: components["schemas"]["WeekProjectionResponse"][];
            /** Actions */
            actions: components["schemas"]["PreparatoryActionResponse"][];
            /** Resources */
            resources: components["schemas"]["OfficialResourceResponse"][];
            /** Disclaimers */
            disclaimers: string[];
        };
        /** ScenarioSummaryResponse */
        ScenarioSummaryResponse: {
            /** Horizon Weeks */
            horizon_weeks: number;
            /** Weeks Affected */
            weeks_affected: number;
            /** Recovery Weeks */
            recovery_weeks: number;
            /** Weekly Net Work Income During Shock Cents */
            weekly_net_work_income_during_shock_cents: number;
            /** Weekly Net Cash Flow During Shock Cents */
            weekly_net_cash_flow_during_shock_cents: number;
            /** Unexpected Cost Cents */
            unexpected_cost_cents: number;
            /** Total Income Lost Cents */
            total_income_lost_cents: number;
            /** Lowest Buffer Cents */
            lowest_buffer_cents: number;
            /** Lowest Buffer Week */
            lowest_buffer_week: number;
            /** Buffer Runway Weeks */
            buffer_runway_weeks: number | null;
            /** First Shortfall Week */
            first_shortfall_week: number | null;
            /** Total Shortfall Cents */
            total_shortfall_cents: number;
            /** Buffer At Horizon Cents */
            buffer_at_horizon_cents: number;
            /** Buffer Holds Through Horizon */
            buffer_holds_through_horizon: boolean;
            /** Full Income Resumes Week */
            full_income_resumes_week: number | null;
        };
        /** SchemeResult */
        SchemeResult: {
            /** Rule Id */
            rule_id: string;
            /** Name */
            name: string;
            /** Agency */
            agency: string;
            status: components["schemas"]["SchemeStatus"];
            /** Matched Facts */
            matched_facts?: string[];
            /** Unmatched Reasons */
            unmatched_reasons?: string[];
            /** Missing Fields */
            missing_fields?: string[];
            /** Official Source Url */
            official_source_url: string;
            /** Application Url */
            application_url: string;
            /**
             * Last Reviewed Date
             * Format: date
             */
            last_reviewed_date: string;
            /** Simplified Note */
            simplified_note: string;
        };
        /**
         * SchemeStatus
         * @enum {string}
         */
        SchemeStatus: "matched" | "not_matched" | "missing_information";
        /** SelectOption */
        SelectOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** ShockScenarioPayload */
        ShockScenarioPayload: {
            /** Income Reduction Percent */
            income_reduction_percent: number;
            /** Weeks Affected */
            weeks_affected: number;
            /**
             * Unexpected Cost Cents
             * @default 0
             */
            unexpected_cost_cents: number;
            /**
             * Recovery Weeks
             * @default 0
             */
            recovery_weeks: number;
            /** Horizon Weeks */
            horizon_weeks?: number | null;
        };
        /** SimulationRequest */
        SimulationRequest: {
            baseline: components["schemas"]["BaselineFinancesPayload"];
            scenario: components["schemas"]["ShockScenarioPayload"];
        };
        /**
         * TargetFrequency
         * @enum {string}
         */
        TargetFrequency: "weekly" | "monthly";
        /** TransactionInput */
        TransactionInput: {
            /**
             * Entrytype
             * @enum {string}
             */
            entryType: "income" | "cost";
            /** Amountcents */
            amountCents: number;
            /** Description */
            description?: string | null;
            /**
             * Occurredon
             * Format: date
             */
            occurredOn: string;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Entrytype
             * @enum {string}
             */
            entryType: "income" | "cost";
            /** Amountcents */
            amountCents: number;
            /** Description */
            description?: string | null;
            /**
             * Occurredon
             * Format: date
             */
            occurredOn: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** TrendSummaryOut */
        TrendSummaryOut: {
            /** Weeks Considered */
            weeks_considered: number;
            /** Average Net Income Cents */
            average_net_income_cents: number;
            /** Min Net Income Cents */
            min_net_income_cents: number;
            /** Max Net Income Cents */
            max_net_income_cents: number;
            /** Stdev Net Income Cents */
            stdev_net_income_cents: number;
            /** Conservative Weekly Income Cents */
            conservative_weekly_income_cents: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariableCostInput */
        VariableCostInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "fuel" | "charging" | "tolls" | "parking" | "repairs" | "platform_fees" | "cpf" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
        };
        /** WeekBreakdownOut */
        WeekBreakdownOut: {
            /** Week Start */
            week_start: string;
            /** Gross Earnings Cents */
            gross_earnings_cents: number;
            /** Platform Breakdown */
            platform_breakdown: components["schemas"]["PlatformEarningOut"][];
            /** Work Costs Cents */
            work_costs_cents: number;
            /** Cpf Cents */
            cpf_cents: number;
            /** Net Income Cents */
            net_income_cents: number;
            /** Essential Expenses Cents */
            essential_expenses_cents: number;
            /** Surplus Cents */
            surplus_cents: number;
        };
        /** WeekProjectionResponse */
        WeekProjectionResponse: {
            /** Week */
            week: number;
            /** Gross Earnings Cents */
            gross_earnings_cents: number;
            /** Work Costs Cents */
            work_costs_cents: number;
            /** Net Work Income Cents */
            net_work_income_cents: number;
            /** Essential Expenses Cents */
            essential_expenses_cents: number;
            /** One Off Cost Cents */
            one_off_cost_cents: number;
            /** Net Cash Flow Cents */
            net_cash_flow_cents: number;
            /** Buffer Open Cents */
            buffer_open_cents: number;
            /** Buffer Close Cents */
            buffer_close_cents: number;
            /** Shortfall Cents */
            shortfall_cents: number;
        };
        /** WeeklyEntryIn */
        WeeklyEntryIn: {
            /**
             * Week Start
             * @description ISO 8601 date, Monday of the week
             */
            week_start: string;
            /** Platform Earnings */
            platform_earnings?: components["schemas"]["PlatformEarningIn"][];
            /**
             * Work Costs Cents
             * @default 0
             */
            work_costs_cents: number;
            /**
             * Essential Expenses Cents
             * @default 0
             */
            essential_expenses_cents: number;
            /**
             * Recorded Cpf Cents
             * @description Actual recorded CPF/MediSave amount; overrides the estimate for this week
             */
            recorded_cpf_cents?: number | null;
        };
        /** WeeklyEntryResponse */
        WeeklyEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Weekstart
             * Format: date
             */
            weekStart: string;
            /** Hadnoincome */
            hadNoIncome: boolean;
            /** Emergencysavingscents */
            emergencySavingsCents: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "confirmed";
            /** Revision */
            revision: number;
            /** Earnings */
            earnings: components["schemas"]["EarningInput"][];
            /** Variablecosts */
            variableCosts: components["schemas"]["VariableCostInput"][];
            /** Inputsnapshots */
            inputSnapshots: components["schemas"]["InputSnapshot"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** WeeklyEntryUpsert */
        WeeklyEntryUpsert: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Expectedrevision */
            expectedRevision?: number | null;
            /**
             * Hadnoincome
             * @default false
             */
            hadNoIncome: boolean;
            /** Emergencysavingscents */
            emergencySavingsCents: number;
            /**
             * Status
             * @default confirmed
             * @enum {string}
             */
            status: "draft" | "confirmed";
            /** Earnings */
            earnings?: components["schemas"]["EarningInput"][];
            /** Variablecosts */
            variableCosts?: components["schemas"]["VariableCostInput"][];
            /** Inputsnapshots */
            inputSnapshots?: components["schemas"]["InputSnapshot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_api_v1_foundation_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBootstrap"];
                };
            };
        };
    };
    onboarding_api_v1_foundation_onboarding_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBootstrap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_update_api_v1_foundation_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recurring_put_api_v1_foundation_recurring_work_costs__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringWorkCostInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringWorkCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recurring_delete_api_v1_foundation_recurring_work_costs__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    essential_put_api_v1_foundation_essential_expenses__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EssentialExpenseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EssentialExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    essential_delete_api_v1_foundation_essential_expenses__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weeks_list_api_v1_foundation_weeks_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_get_api_v1_foundation_weeks__week_start__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_put_api_v1_foundation_weeks__week_start__put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyEntryUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_delete_api_v1_foundation_weeks__week_start__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transaction_create_api_v1_foundation_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transaction_delete_api_v1_foundation_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_reset_api_v1_foundation_data_delete: {
        parameters: {
            query?: never;
            header: {
                "X-Confirm-Reset": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBootstrap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_breakdown_api_v1_income_reality_breakdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeRealityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeRealityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_questionnaire_api_v1_scheme_navigator_questionnaire_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionnaireField"][];
                };
            };
        };
    };
    evaluate_api_v1_scheme_navigator_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_result_api_v1_scheme_navigator_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplanationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplanationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_turn_api_v1_scheme_navigator_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_scenario_api_v1_scenario_simulator_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_v1_savings_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalListResponse"];
                };
            };
        };
    };
    create_goal_api_v1_savings_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_goal_api_v1_savings_goals__goal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_goal_api_v1_savings_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_contribution_api_v1_savings_goals__goal_id__contributions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsGoalContributionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsGoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contribution_api_v1_savings_goals__goal_id__contributions__contribution_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
                contribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_resilience_jar_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    patch_plan_api_v1_resilience_jar_plan_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_opening_balance_api_v1_resilience_jar_opening_balance_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpeningBalanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contribution_api_v1_resilience_jar_contributions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_withdrawal_api_v1_resilience_jar_withdrawals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contribution_api_v1_resilience_jar_contributions__contribution_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contribution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contribution_api_v1_resilience_jar_contributions__contribution_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contribution_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
