/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/foundation/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_api_v1_foundation_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Onboarding */
        put: operations["onboarding_api_v1_foundation_onboarding_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Profile Update */
        patch: operations["profile_update_api_v1_foundation_profile_patch"];
        trace?: never;
    };
    "/api/v1/foundation/recurring-work-costs/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Recurring Put */
        put: operations["recurring_put_api_v1_foundation_recurring_work_costs__item_id__put"];
        post?: never;
        /** Recurring Delete */
        delete: operations["recurring_delete_api_v1_foundation_recurring_work_costs__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/essential-expenses/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Essential Put */
        put: operations["essential_put_api_v1_foundation_essential_expenses__item_id__put"];
        post?: never;
        /** Essential Delete */
        delete: operations["essential_delete_api_v1_foundation_essential_expenses__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weeks List */
        get: operations["weeks_list_api_v1_foundation_weeks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/weeks/{week_start}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Week Get */
        get: operations["week_get_api_v1_foundation_weeks__week_start__get"];
        /** Week Put */
        put: operations["week_put_api_v1_foundation_weeks__week_start__put"];
        post?: never;
        /** Week Delete */
        delete: operations["week_delete_api_v1_foundation_weeks__week_start__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/imports/csv/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csv Template */
        get: operations["csv_template_api_v1_foundation_imports_csv_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/imports/csv/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Csv Preview */
        post: operations["csv_preview_api_v1_foundation_imports_csv_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/foundation/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Data Reset */
        delete: operations["data_reset_api_v1_foundation_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-reality/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Breakdown */
        post: operations["post_breakdown_api_v1_income_reality_breakdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssumptionsIn */
        AssumptionsIn: {
            /**
             * Apply Cpf
             * @default false
             */
            apply_cpf: boolean;
            /**
             * Cpf Rate Bps
             * @default 800
             */
            cpf_rate_bps: number;
        };
        /** Body_csv_preview_api_v1_foundation_imports_csv_preview_post */
        Body_csv_preview_api_v1_foundation_imports_csv_preview_post: {
            /** File */
            file: string;
        };
        /** CsvPreviewResponse */
        CsvPreviewResponse: {
            /** Filename */
            fileName: string;
            /** Filesha256 */
            fileSha256: string;
            /** Rows */
            rows: components["schemas"]["CsvPreviewRow"][];
            /** Validcount */
            validCount: number;
            /** Invalidcount */
            invalidCount: number;
        };
        /** CsvPreviewRow */
        CsvPreviewRow: {
            /** Rownumber */
            rowNumber: number;
            /**
             * Status
             * @enum {string}
             */
            status: "valid" | "invalid";
            /** Weekstart */
            weekStart?: string | null;
            /** Recordtype */
            recordType?: ("earning" | "variable_work_cost") | null;
            /** Source */
            source?: string | null;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Amountcents */
            amountCents?: number | null;
            /** Errors */
            errors?: string[];
        };
        /** EarningInput */
        EarningInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Platformcode
             * @enum {string}
             */
            platformCode: "grab" | "gojek" | "tada" | "deliveroo" | "foodpanda" | "lalamove" | "other";
            /** Platformlabel */
            platformLabel?: string | null;
            /** Amountcents */
            amountCents: number;
        };
        /** EssentialExpenseInput */
        EssentialExpenseInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "housing" | "food" | "transport" | "utilities" | "healthcare" | "caregiving" | "debt" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
        };
        /** EssentialExpenseResponse */
        EssentialExpenseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "housing" | "food" | "transport" | "utilities" | "healthcare" | "caregiving" | "debt" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** FoundationBootstrap */
        FoundationBootstrap: {
            profile: components["schemas"]["ProfileResponse"];
            /** Recurringworkcosts */
            recurringWorkCosts: components["schemas"]["RecurringWorkCostResponse"][];
            /** Essentialexpenses */
            essentialExpenses: components["schemas"]["EssentialExpenseResponse"][];
            /** Weeklyentries */
            weeklyEntries: components["schemas"]["WeeklyEntryResponse"][];
            /**
             * Syncedat
             * Format: date-time
             */
            syncedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeRealityRequest */
        IncomeRealityRequest: {
            /** Weeks */
            weeks: components["schemas"]["WeeklyEntryIn"][];
            assumptions?: components["schemas"]["AssumptionsIn"];
        };
        /** IncomeRealityResponse */
        IncomeRealityResponse: {
            /** Weeks */
            weeks: components["schemas"]["WeekBreakdownOut"][];
            trend: components["schemas"]["TrendSummaryOut"];
            assumptions_applied: components["schemas"]["AssumptionsIn"];
        };
        /** InputSnapshot */
        InputSnapshot: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sourceid */
            sourceId?: string | null;
            /**
             * Inputkind
             * @enum {string}
             */
            inputKind: "recurring_work_cost" | "essential_expense";
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /** Emergencysavingscents */
            emergencySavingsCents: number;
            /** Recurringworkcosts */
            recurringWorkCosts?: components["schemas"]["RecurringWorkCostInput"][];
            /** Essentialexpenses */
            essentialExpenses?: components["schemas"]["EssentialExpenseInput"][];
            /** Firstweekstart */
            firstWeekStart?: string | null;
            firstWeek?: components["schemas"]["WeeklyEntryUpsert"] | null;
        };
        /** PlatformEarningIn */
        PlatformEarningIn: {
            /** Platform */
            platform: string;
            /** Gross Cents */
            gross_cents: number;
        };
        /** PlatformEarningOut */
        PlatformEarningOut: {
            /** Platform */
            platform: string;
            /** Gross Cents */
            gross_cents: number;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Currency */
            currency: string;
            /** Timezone */
            timezone: string;
            /** Onboardingcompleted */
            onboardingCompleted: boolean;
            /** Latestemergencysavingscents */
            latestEmergencySavingsCents: number;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Latestemergencysavingscents */
            latestEmergencySavingsCents: number;
        };
        /** RecurringWorkCostInput */
        RecurringWorkCostInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "vehicle_rental" | "insurance" | "subscription" | "equipment" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
        };
        /** RecurringWorkCostResponse */
        RecurringWorkCostResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "vehicle_rental" | "insurance" | "subscription" | "equipment" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
            /**
             * Cadence
             * @enum {string}
             */
            cadence: "weekly" | "monthly";
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** TrendSummaryOut */
        TrendSummaryOut: {
            /** Weeks Considered */
            weeks_considered: number;
            /** Average Net Income Cents */
            average_net_income_cents: number;
            /** Min Net Income Cents */
            min_net_income_cents: number;
            /** Max Net Income Cents */
            max_net_income_cents: number;
            /** Stdev Net Income Cents */
            stdev_net_income_cents: number;
            /** Conservative Weekly Income Cents */
            conservative_weekly_income_cents: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariableCostInput */
        VariableCostInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category
             * @enum {string}
             */
            category: "fuel" | "charging" | "tolls" | "parking" | "repairs" | "platform_fees" | "cpf" | "other";
            /** Label */
            label: string;
            /** Amountcents */
            amountCents: number;
        };
        /** WeekBreakdownOut */
        WeekBreakdownOut: {
            /** Week Start */
            week_start: string;
            /** Gross Earnings Cents */
            gross_earnings_cents: number;
            /** Platform Breakdown */
            platform_breakdown: components["schemas"]["PlatformEarningOut"][];
            /** Work Costs Cents */
            work_costs_cents: number;
            /** Cpf Cents */
            cpf_cents: number;
            /** Net Income Cents */
            net_income_cents: number;
            /** Essential Expenses Cents */
            essential_expenses_cents: number;
            /** Surplus Cents */
            surplus_cents: number;
        };
        /** WeeklyEntryIn */
        WeeklyEntryIn: {
            /**
             * Week Start
             * @description ISO 8601 date, Monday of the week
             */
            week_start: string;
            /** Platform Earnings */
            platform_earnings?: components["schemas"]["PlatformEarningIn"][];
            /**
             * Work Costs Cents
             * @default 0
             */
            work_costs_cents: number;
            /**
             * Essential Expenses Cents
             * @default 0
             */
            essential_expenses_cents: number;
            /**
             * Recorded Cpf Cents
             * @description Actual recorded CPF/MediSave amount; overrides the estimate for this week
             */
            recorded_cpf_cents?: number | null;
        };
        /** WeeklyEntryResponse */
        WeeklyEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Weekstart
             * Format: date
             */
            weekStart: string;
            /** Hadnoincome */
            hadNoIncome: boolean;
            /** Emergencysavingscents */
            emergencySavingsCents: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "confirmed";
            /** Revision */
            revision: number;
            /** Earnings */
            earnings: components["schemas"]["EarningInput"][];
            /** Variablecosts */
            variableCosts: components["schemas"]["VariableCostInput"][];
            /** Inputsnapshots */
            inputSnapshots: components["schemas"]["InputSnapshot"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** WeeklyEntryUpsert */
        WeeklyEntryUpsert: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Expectedrevision */
            expectedRevision?: number | null;
            /**
             * Hadnoincome
             * @default false
             */
            hadNoIncome: boolean;
            /** Emergencysavingscents */
            emergencySavingsCents: number;
            /**
             * Status
             * @default confirmed
             * @enum {string}
             */
            status: "draft" | "confirmed";
            /** Earnings */
            earnings?: components["schemas"]["EarningInput"][];
            /** Variablecosts */
            variableCosts?: components["schemas"]["VariableCostInput"][];
            /** Inputsnapshots */
            inputSnapshots?: components["schemas"]["InputSnapshot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrap_api_v1_foundation_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBootstrap"];
                };
            };
        };
    };
    onboarding_api_v1_foundation_onboarding_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBootstrap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_update_api_v1_foundation_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recurring_put_api_v1_foundation_recurring_work_costs__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecurringWorkCostInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringWorkCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recurring_delete_api_v1_foundation_recurring_work_costs__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    essential_put_api_v1_foundation_essential_expenses__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EssentialExpenseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EssentialExpenseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    essential_delete_api_v1_foundation_essential_expenses__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weeks_list_api_v1_foundation_weeks_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_get_api_v1_foundation_weeks__week_start__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_put_api_v1_foundation_weeks__week_start__put: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyEntryUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_delete_api_v1_foundation_weeks__week_start__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                week_start: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    csv_template_api_v1_foundation_imports_csv_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    csv_preview_api_v1_foundation_imports_csv_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_csv_preview_api_v1_foundation_imports_csv_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_reset_api_v1_foundation_data_delete: {
        parameters: {
            query?: never;
            header: {
                "X-Confirm-Reset": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationBootstrap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_breakdown_api_v1_income_reality_breakdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeRealityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeRealityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
